"""Global configuration for the Maritime Route Planning application.

全局配置模块：集中管理路径、类别定义、模型超参数与航行代价权重。
All tunable constants live here so that the rest of the code base never
hard-codes a path, a class index or a cost weight.

Contents
--------
* **Project layout** - absolute paths of the data, model, output and
  documentation directories. Three of them can be overridden through
  environment variables (``MR_DATA_DIR``, ``MR_MODEL_DIR``, ``MR_OUTPUT_DIR``)
  and the SQLite database through ``MR_DB_PATH``, so that tests and
  deployments can redirect all file I/O without editing code.
* **Zone taxonomy** - the four classes predicted by the neural network, their
  descriptions, colours and traversal costs used by the route planner.
* **Regions** - bounding boxes of the ten sea regions of the labelled corpus,
  used for per-region statistics and evaluation.
* **Feature extraction** - OSM column names and neighbourhood sizes used by
  :mod:`maritime_route.data.features`.
* **Hyper-parameters** - frozen dataclasses :class:`TrainingConfig`,
  :class:`RoutingConfig`, :class:`GeneticConfig` and :class:`ServerConfig`, each
  with one module-level default instance (``TRAINING``, ``ROUTING``,
  ``GENETIC``, ``SERVER``). The dataclasses are frozen so that a shared default
  cannot be modified by accident; a variant is created with
  :func:`dataclasses.replace`.

Side effect: importing this module creates the data/model/output/figure
directories if they do not exist yet.

内容：项目路径、四类区域定义与配色、航行代价、海域范围、特征参数，以及训练、
航线规划、遗传算法和 Web 服务的超参数（冻结数据类，修改需用 dataclasses.replace）。
导入本模块会自动创建所需目录。
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Tuple

# --------------------------------------------------------------------------- #
# Project layout                                                              #
# --------------------------------------------------------------------------- #
# The three roots are derived from the location of this file:
#   <PROJECT_ROOT>/src/maritime_route/config.py
# so the code works wherever the repository is checked out.
# 三个根目录由本文件位置推导，与仓库所在路径无关。

#: Directory of the ``maritime_route`` package itself. 包目录。
PACKAGE_ROOT: Path = Path(__file__).resolve().parent
#: The ``src`` directory that contains the package. src 目录。
SRC_ROOT: Path = PACKAGE_ROOT.parent
#: Repository root (contains ``data``, ``models``, ``docs``, ``scripts``). 项目根目录。
PROJECT_ROOT: Path = SRC_ROOT.parent

#: Root of all data files; override with the ``MR_DATA_DIR`` environment variable.
#: 数据根目录，可用环境变量 MR_DATA_DIR 覆盖。
DATA_DIR: Path = Path(os.environ.get("MR_DATA_DIR", PROJECT_ROOT / "data"))
#: Raw, unprocessed input corpora (GeoJSON). 原始数据。
RAW_DIR: Path = DATA_DIR / "raw"
#: Output of ``scripts/prepare_dataset.py``: feature matrices and statistics. 预处理结果。
PROCESSED_DIR: Path = DATA_DIR / "processed"
#: Small example files for demonstrations and the UI. 示例数据。
SAMPLE_DIR: Path = DATA_DIR / "samples"
#: Trained weights, scaler, reference index, metadata; override with ``MR_MODEL_DIR``.
#: 模型文件目录，可用 MR_MODEL_DIR 覆盖。
MODEL_DIR: Path = Path(os.environ.get("MR_MODEL_DIR", PROJECT_ROOT / "models"))
#: Exported routes (GeoJSON/CSV/PDF); override with ``MR_OUTPUT_DIR``. 导出文件目录。
OUTPUT_DIR: Path = Path(os.environ.get("MR_OUTPUT_DIR", PROJECT_ROOT / "outputs"))
#: Thesis documentation. 文档目录。
DOCS_DIR: Path = PROJECT_ROOT / "docs"
#: Figures generated by ``scripts/make_figures.py`` and related scripts. 图表输出目录。
FIGURE_DIR: Path = DOCS_DIR / "figures"

#: Default labelled corpus read by ``scripts/prepare_dataset.py``. 默认原始语料。
DEFAULT_RAW_DATASET: Path = RAW_DIR / "merged.geojson"
#: SQLite database of saved routes and uploads; override with ``MR_DB_PATH``.
#: SQLite 数据库路径，可用 MR_DB_PATH 覆盖。
DATABASE_PATH: Path = Path(os.environ.get("MR_DB_PATH", DATA_DIR / "maritime_route.db"))

# Create the writable directories once at import time so that no other module
# has to check for their existence before writing. exist_ok makes it idempotent.
# 导入时一次性创建可写目录，其他模块写文件前无需再检查；exist_ok 保证可重复执行。
for _d in (RAW_DIR, PROCESSED_DIR, SAMPLE_DIR, MODEL_DIR, OUTPUT_DIR, FIGURE_DIR):
    _d.mkdir(parents=True, exist_ok=True)

# --------------------------------------------------------------------------- #
# Geographic zone taxonomy (four classes required by the assignment)          #
# --------------------------------------------------------------------------- #
#: The four zone classes. The list order defines the integer class index used
#: by the network output layer (index 0 = OPEN_SEA ... 3 = COASTLINE), so it must
#: not be changed after a model has been trained.
#: 四个区域类别；列表顺序即网络输出的类别索引，训练后不可更改。
CLASS_NAMES: List[str] = ["OPEN_SEA", "COASTAL_SEA", "NEAR_COAST", "COASTLINE"]
#: Class name -> integer index (used to encode labels). 类别名 -> 索引。
CLASS_TO_INDEX: Dict[str, int] = {name: i for i, name in enumerate(CLASS_NAMES)}
#: Integer index -> class name (used to decode ``argmax`` of the network). 索引 -> 类别名。
INDEX_TO_CLASS: Dict[int, str] = {i: name for name, i in CLASS_TO_INDEX.items()}

#: Human readable descriptions used by the UI and the PDF report.
#: Note: the code ``COASTLINE`` historically denotes *inland* land, i.e. land
#: remote from the sea, while ``NEAR_COAST`` is land within 5 km of the shore.
#: 注意：COASTLINE 实际表示远离海岸的内陆，NEAR_COAST 表示距海岸 5 km 以内的陆地。
CLASS_DESCRIPTION: Dict[str, str] = {
    "OPEN_SEA": "Open sea - deep water far from any shoreline",
    "COASTAL_SEA": "Coastal sea - navigable water close to the shore",
    "NEAR_COAST": "Near coast - land within 5 km of the shoreline",
    "COASTLINE": "Inland - land remote from the sea",
}

# The four zones are ordinal around sea level (deep water -> shallow water ->
# shore -> inland), so they are encoded with a DIVERGING hypsometric scheme:
# two hues (water blue / land ochre) whose lightness is monotone within each
# pole and whose neutral midpoint is the coastline itself. This is the standard
# cartographic depth/height tint and, unlike a categorical palette, it also
# conveys the ordering of the classes.
# 四个区域沿海平面呈有序分布，因此采用"发散型"等深-等高配色：
# 水域蓝 / 陆地赭，海岸线为中性中点，每一极内部亮度单调变化。
#
# Separation was verified numerically (OKLab dE x100, all pairs):
#   light  - worst CVD dE 15.8 (protan), normal-vision dE 20.2
#   dark   - worst CVD dE 14.8 (protan), normal-vision dE 16.8
# Both clear the >=8 CVD and >=15 normal-vision gates. The two light tints fall
# below 3:1 contrast on white, so every figure and map carries direct labels or
# a legend - colour never encodes identity on its own.
# (CVD = colour vision deficiency; dE = perceptual colour difference.)
# （CVD 指色觉缺陷；dE 为感知色差。）

#: Print / figure / export palette (light surfaces). Hex RGB strings.
#: Used by the GeoJSON/PDF exporters and the database seed. 打印/导出用浅色底配色。
CLASS_COLOR: Dict[str, str] = {
    "OPEN_SEA": "#14507f",
    "COASTAL_SEA": "#6bb3d6",
    "NEAR_COAST": "#e8c88c",
    "COASTLINE": "#8a5a2b",
}

#: Same ramp re-stepped for the dark user interface and the on-board tiles.
#: Used by the web API legend and the raster tile renderer. 深色界面与地图瓦片配色。
CLASS_COLOR_DARK: Dict[str, str] = {
    "OPEN_SEA": "#3d7fb8",
    "COASTAL_SEA": "#7cc3e3",
    "NEAR_COAST": "#d9b877",
    "COASTLINE": "#a9763f",
}

#: Categorical slots for statistical series (training curves, algorithm bars).
#: ``grid`` is the colour of chart grid lines, ``neutral`` of reference lines.
#: 统计图表的分类配色（已通过色觉与对比度校验）。
SERIES_COLOR: Dict[str, str] = {
    "primary": "#2a78d6",
    "secondary": "#eb6834",
    "tertiary": "#1baf7a",
    "quaternary": "#4a3aa7",
    "neutral": "#52514e",
    "grid": "#d8d8d4",
}

#: Traversal cost multiplier per zone. Navigable zones are cheap, land is
#: effectively impassable. 通行代价权重：数值越大越不适合航行。
#: The cost of a grid step is (step length in km) x (multiplier of the cell), so
#: the value is dimensionless. Open sea is the reference (1.0). Coastal sea costs
#: 1.8, i.e. the planner accepts a detour of up to 80 % in open water to avoid a
#: stretch of coastal water (shallower, denser traffic). Land is infinite and is
#: stored as :data:`IMPASSABLE_COST` in numeric rasters.
#: 每步代价 = 步长(km) × 单元权重（无量纲）。近岸海 1.8 意味着为避开近岸水域可接受
#: 最多 80% 的远海绕行；陆地为无穷大，在数值栅格中以 IMPASSABLE_COST 表示。
ZONE_COST: Dict[str, float] = {
    "OPEN_SEA": 1.0,
    "COASTAL_SEA": 1.8,
    "NEAR_COAST": float("inf"),
    "COASTLINE": float("inf"),
}

#: Finite stand-in used when the planner is asked to allow land crossing
#: (debug mode) and inside numeric cost rasters that cannot store infinity.
#: Search algorithms treat any cell with cost >= this value as a wall. 1e6 is
#: several orders of magnitude above any real water cost, so a single land cell
#: always outweighs any water detour.
#: 代价 >= 该值的单元被视为不可通行；1e6 远大于任何水域代价。
IMPASSABLE_COST: float = 1.0e6

#: Classes a ship may sail through; all other classes are land.
#: 可航行的类别；其余类别均为陆地。
NAVIGABLE_CLASSES: Tuple[str, ...] = ("OPEN_SEA", "COASTAL_SEA")

#: Classes that describe water and classes that describe land. A labelled point
#: whose class disagrees with the sign of its measured height/depth is treated
#: as a labelling error (see :mod:`maritime_route.data.cleaning`).
#: 水域类与陆地类；类别与实测高程/水深符号矛盾的样本视为标注错误。
WATER_CLASSES: Tuple[str, ...] = ("OPEN_SEA", "COASTAL_SEA")
LAND_CLASSES: Tuple[str, ...] = ("NEAR_COAST", "COASTLINE")

#: Tolerance of the label/measurement consistency check, metres. A sea point
#: may lie up to this height above zero (tide, DEM error) and a land point up to
#: this depth below zero before it is considered mislabelled.
#: 一致性检查容差（米），用于吸收潮汐与高程模型误差。
LABEL_CHECK_TOLERANCE_M: float = 5.0

# --------------------------------------------------------------------------- #
# Geographic regions of the corpus                                            #
# --------------------------------------------------------------------------- #
#: The labelled corpus was collected in ten separate sea regions. Each region
#: is described by a bounding box (lat_min, lat_max, lon_min, lon_max); boxes
#: are tested in order and the first match wins. Points outside every box
#: (inland samples far from any of the seas) are reported as "Other".
#: Units: decimal degrees (WGS84); lower bounds inclusive, upper bounds exclusive.
#: 语料覆盖的十个海域，按经纬度范围划分，依次匹配，均不匹配者记为 Other。
#: 单位为十进制度（WGS84）；下界包含，上界不包含。
REGIONS: List[Tuple[str, Tuple[float, float, float, float]]] = [
    ("North Europe (Baltic and North Sea)",      (47.5, 68.0, -40.0, 33.0)),
    ("Red Sea and Gulf of Aden",                 (5.0, 30.0, 32.0, 52.0)),
    ("Black Sea and Eastern Mediterranean",      (29.0, 47.5, 19.0, 42.5)),
    ("Persian Gulf and Arabian Sea",             (5.0, 31.5, 48.0, 70.0)),
    ("Bay of Bengal",                            (10.0, 25.0, 78.0, 93.0)),
    ("Strait of Malacca and Andaman Sea",        (-1.0, 10.0, 92.0, 105.0)),
    ("South China Sea",                          (-1.0, 26.0, 103.0, 125.0)),
    ("Japan and North-West Pacific",             (19.0, 48.0, 125.0, 165.0)),
    ("Southern Africa (Cape of Good Hope)",      (-42.0, -28.0, 13.0, 32.0)),
    ("Central America (Caribbean coast)",        (4.0, 18.0, -90.0, -76.0)),
]

# --------------------------------------------------------------------------- #
# Feature extraction                                                          #
# --------------------------------------------------------------------------- #
#: OpenStreetMap object counts stored with every labelled point (number of
#: objects of each type near the point). The order defines the last axis of
#: ``ReferenceIndex.osm_counts``; missing columns are filled with 0 on load.
#: 每个样本附带的 OSM 对象计数列；顺序决定参考索引中 osm_counts 的列顺序。
OSM_COLUMNS: List[str] = [
    "osm_piers",
    "osm_lighthouses",
    "osm_breakwaters",
    "osm_harbors",
    "osm_rivers",
    "osm_lakes",
    "osm_beaches",
    "osm_cliffs",
    "osm_industrial",
]

#: Number of bathymetric reference samples queried around every point.
#: k = 8 neighbours give a stable mean/std/min/max of the local relief while
#: keeping the neighbourhood small (a few km in the dense corpus).
#: 每个点查询的邻近参考样本数 k。
BATHY_NEIGHBOURS: int = 8
#: Radius (km) inside which OSM objects are aggregated for a query point.
#: In :func:`maritime_route.data.features.build_features` it is used only as a
#: floor: 10 % of it (1.2 km) is the minimum neighbourhood span when the OSM
#: density per km is computed, which prevents division by a near-zero distance.
#: OSM 聚合半径（km）；特征计算中取其 10%（1.2 km）作为密度分母的下限。
OSM_RADIUS_KM: float = 12.0
#: Mean Earth radius, km (IUGG value). Converts haversine angles (radians) to km.
#: 地球平均半径（km），用于将球面角距离（弧度）换算为公里。
EARTH_RADIUS_KM: float = 6371.0088

# --------------------------------------------------------------------------- #
# Neural network hyper-parameters                                             #
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class TrainingConfig:
    """Hyper-parameters of the zone classifier. 神经网络训练超参数。

    Consumed by :func:`maritime_route.model.trainer.train_model` and by
    :func:`maritime_route.data.dataset.prepare` (split sizes and seed).
    The instance is immutable; ``scripts/train_model.py`` creates a modified
    copy with :func:`dataclasses.replace` when command-line options are given.

    Attributes
    ----------
    hidden_sizes:
        Width of each residual block of the MLP. A funnel 256 -> 128 -> 64 on
        a 28-dimensional input gives about 98 k trainable parameters
        (including the skip projections), enough capacity
        for the non-linear coastal boundaries without overfitting.
    dropout:
        Dropout probability applied after every hidden block.
    batch_size:
        Samples per optimiser step.
    epochs:
        Upper bound on the number of passes over the training set; early
        stopping normally ends training earlier.
    learning_rate:
        Initial learning rate of AdamW.
    weight_decay:
        Decoupled L2 regularisation coefficient of AdamW.
    early_stopping_patience:
        Epochs without validation-loss improvement before training stops.
    lr_scheduler_patience:
        Epochs without improvement before the learning rate is halved.
        Smaller than ``early_stopping_patience`` so that the rate is reduced
        (twice) before training is abandoned.
    label_smoothing:
        Probability mass moved from the true class to the other classes in
        the cross-entropy target.
    test_size, val_size:
        Shares of the corpus held out for testing and validation (70/15/15).
    random_seed:
        Seed of the data split, weight initialisation and batch shuffling.
    device:
        PyTorch device string; ``"cpu"`` because the model is small.

    各字段：隐藏层宽度、Dropout、批大小、最大轮数、学习率、权重衰减、早停耐心、
    学习率调度耐心、标签平滑、测试/验证集比例、随机种子与计算设备。
    """

    hidden_sizes: Tuple[int, ...] = (256, 128, 64)  # neurons per residual block 各残差块宽度
    dropout: float = 0.20                  # dropout probability 随机失活概率
    batch_size: int = 512                  # samples per mini-batch 批大小
    epochs: int = 120                      # max epochs (early stopping usually ends earlier) 最大轮数
    learning_rate: float = 1.5e-3          # initial AdamW learning rate 初始学习率
    weight_decay: float = 1.0e-4           # AdamW decoupled weight decay 权重衰减
    early_stopping_patience: int = 15      # epochs without val-loss improvement 早停耐心
    lr_scheduler_patience: int = 6         # epochs before LR is halved 学习率减半前的等待轮数
    label_smoothing: float = 0.02          # 2 % of target mass spread over other classes 标签平滑
    test_size: float = 0.15                # share of the corpus for testing 测试集比例
    val_size: float = 0.15                 # share of the corpus for validation 验证集比例
    random_seed: int = 42                  # reproducibility 随机种子
    device: str = "cpu"                    # PyTorch device 计算设备


#: Default training configuration. 默认训练配置。
TRAINING = TrainingConfig()

# Files written by the trainer / dataset preparation and read by the inference
# service. They must be kept together: the scaler and the reference index are
# part of the model (features are meaningless without them).
# 训练与预处理生成、推理服务读取的文件；标准化器和参考索引与权重必须配套使用。
#: PyTorch checkpoint: ``{"state_dict": ..., "config": ...}``. 网络权重。
MODEL_WEIGHTS_PATH: Path = MODEL_DIR / "zone_classifier.pt"
#: JSON with hyper-parameters, test metrics and training history. 模型元数据。
MODEL_METADATA_PATH: Path = MODEL_DIR / "model_metadata.json"
#: Fitted :class:`sklearn.preprocessing.StandardScaler` (joblib). 特征标准化器。
SCALER_PATH: Path = MODEL_DIR / "feature_scaler.joblib"
#: Label-free :class:`~maritime_route.data.features.ReferenceIndex` (.npz). 参考索引。
BATHY_INDEX_PATH: Path = MODEL_DIR / "reference_index.npz"

# --------------------------------------------------------------------------- #
# Routing                                                                     #
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class RoutingConfig:
    """Default parameters of the grid based route planner. 航线规划默认参数。

    Used by :mod:`maritime_route.routing.cost_map`, ``astar``, ``dijkstra`` and
    ``planner``.

    Attributes
    ----------
    grid_resolution_deg:
        Side of one lattice cell, degrees (0.25 deg is about 28 km of latitude).
    max_grid_cells:
        Cell budget of one cost map. If the bounding box needs more cells, the
        resolution is coarsened by a factor 1.5 until it fits (the network has
        to classify every cell, so this bounds the classification time).
    margin_deg:
        Margin added around the bounding box of the waypoints, degrees, so the
        route can bend around a headland that lies outside the direct box.
    diagonal_moves:
        ``True`` - 8-connected lattice (N, S, E, W and diagonals); ``False`` -
        4-connected.
    heuristic_weight:
        Multiplier of the A* great-circle heuristic. 1.0 keeps the heuristic
        admissible (optimal path); values > 1 give a faster, possibly
        sub-optimal weighted A*.
    safety_margin_cells:
        Width, in cells, of the band of water next to land whose cost is
        multiplied by ``proximity_penalty``.
    proximity_penalty:
        Extra multiplicative penalty applied to a cell adjacent to land.

    各字段：网格分辨率（度）、单元数上限、边界余量（度）、是否允许对角移动、
    A* 启发函数权重、近岸安全带宽度（单元数）与近岸惩罚系数。
    """

    grid_resolution_deg: float = 0.25      # cell size, degrees 网格分辨率（度）
    max_grid_cells: int = 400_000          # cell budget before coarsening 单元数上限
    margin_deg: float = 2.0                # bbox margin, degrees 边界余量（度）
    diagonal_moves: bool = True            # 8-neighbour moves 八邻域移动
    heuristic_weight: float = 1.0          # 1.0 = admissible A* 启发权重
    safety_margin_cells: int = 1           # width of the near-land band, cells 近岸安全带宽度
    #: Extra multiplicative penalty applied to a cell adjacent to land.
    #: Water cells in the safety band cost 1.6x their zone cost (capped below
    #: IMPASSABLE_COST), which keeps routes one cell off the shore when possible.
    #: 近岸惩罚系数：安全带内的水域单元代价乘以 1.6。
    proximity_penalty: float = 1.6


#: Default routing configuration. 默认航线规划配置。
ROUTING = RoutingConfig()


@dataclass(frozen=True)
class GeneticConfig:
    """Parameters of the genetic-algorithm route search.

    A chromosome is a list of intermediate waypoints (lattice cells); the route
    is the chain of straight lattice lines start -> w1 -> ... -> wk -> goal.
    See :mod:`maritime_route.routing.genetic` for the operators.
    遗传算法参数：染色体为中间航点序列，航线由相邻航点之间的直线段连接而成。
    """

    population_size: int = 80          # individuals per generation 种群规模
    generations: int = 300             # upper limit of generations 最大代数
    stagnation_limit: int = 60         # stop after this many generations without improvement
    tournament_size: int = 3           # tournament selection 锦标赛规模
    crossover_rate: float = 0.9        # probability of one-point crossover 交叉概率
    mutation_rate: float = 0.35        # probability that a child is mutated 变异概率
    elite: int = 2                     # best individuals copied unchanged 精英保留数
    max_waypoints: int = 14            # longest chromosome allowed 最大航点数
    initial_waypoints: Tuple[int, int] = (1, 6)   # length range of random chromosomes
    land_penalty_weight: float = 200.0  # weight of an impassable cell in the fitness
    random_seed: int = 42              # reproducible runs 随机种子
    # stagnation_limit: 连续多少代无改进即停止。
    # initial_waypoints: 随机初始染色体的航点数范围 (最少, 最多)。
    # land_penalty_weight: 适应度中每个陆地单元的惩罚权重（以有限值代替无穷大，
    #   使穿越陆地的个体仍可比较并逐步被修复）。


#: Default genetic-algorithm configuration. 默认遗传算法配置。
GENETIC = GeneticConfig()

#: Algorithm identifiers accepted by the web API and the planner.
#: ``great_circle`` is the direct geodesic baseline without obstacle avoidance.
#: Web 接口与规划器支持的算法；great_circle 为不避障的大圆航线基线。
SUPPORTED_ALGORITHMS: Tuple[str, ...] = ("astar", "dijkstra", "genetic", "dynamic", "great_circle")

# --------------------------------------------------------------------------- #
# Web server                                                                  #
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class ServerConfig:
    """Settings of the FastAPI / Uvicorn web service. Web 服务配置。

    Attributes
    ----------
    host:
        Interface to bind; ``MR_HOST`` environment variable, default loopback
        (127.0.0.1) so the service is not exposed on the network by default.
    port:
        TCP port; ``MR_PORT`` environment variable, default 8000.
    title, version:
        Shown in the OpenAPI documentation of the service.
    progress_interval_s:
        Minimum time between two progress messages sent over the WebSocket
        while a route is computed; throttles traffic to the browser.

    注意：host 与 port 的默认值在导入模块时从环境变量读取一次。
    """

    host: str = os.environ.get("MR_HOST", "127.0.0.1")   # bind address 监听地址
    port: int = int(os.environ.get("MR_PORT", "8000"))   # TCP port 端口
    title: str = "Maritime Route Planner"                # OpenAPI title 服务标题
    version: str = "1.0.0"                               # OpenAPI version 服务版本
    #: Seconds between progress frames pushed over the WebSocket.
    #: WebSocket 进度推送的最小间隔（秒）。
    progress_interval_s: float = 0.15


#: Default server configuration. 默认服务配置。
SERVER = ServerConfig()

#: Application metadata shown in exports, the PDF report and ``__version__``.
#: 应用元数据：版本、作者、所属大学（用于导出文件与报告）。
APP_VERSION: str = "1.0.0"
APP_AUTHOR: str = "Li Haoran"
APP_UNIVERSITY: str = "Brest State Technical University"
